### ISSUE TITLE
Can't repay.

### ISSUE THREAD

**Issue by davidgatti** [0x4447-office/0x4447_webpage_pay#27]
<img width="1194" alt="YouTube 2" src="https://user-images.githubusercontent.com/411114/87229055-63d2c900-c3a5-11ea-83d9-c5edfc5c7234.png">

First transaction works, but if I go back with the back button and try to pay again I can't

**Comment by tolgaouz** [comment]
This is probably caused because you're trying to use the same payment intent to pay again, when you go back. Instead if you refresh the page it'd work

**Comment by davidgatti** [comment]
Cool, so if you know the problem, make it work without me needing to refresh :D
