### ISSUE TITLE
Bringing all to a working point

### ISSUE THREAD

**Issue by davidgatti** [0x4447-office/0x4447_webpage_pay#9]
- Do not use yarn ever in any projects please
- Fix issue with the Stripe SDK complaining about missing info
- remove border again
- On the next page, show a spinner with Loading text, and only once al lis ready display the UI
- add footer to all pages
- Brake out all the functions in to seprate files
- Make functions smaller, so they just do one thing only.

**Comment by tolgaouz** [comment]
hopefully, product should be up and running
